field: 78106212-4541-48ce-9ff4-921c9077a54d # Social Media
fieldLayouts:
  a6d4ea0a-995d-4daf-bf90-3336cfee6adc:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 2d013c9e-bfbc-478c-abf8-805784c3b2a8 # Facebook
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: faa4498f-6293-458f-89ce-16b50e303451
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 38c95122-8782-4768-8afa-393545ab3e8f
        userCondition: null
fields:
  2d013c9e-bfbc-478c-abf8-805784c3b2a8: # Facebook
    columnSuffix: lykzbgao
    contentColumnType: string(255)
    fieldGroup: null
    handle: facebook
    instructions: null
    name: Facebook
    searchable: false
    settings:
      maxLength: 255
      types:
        - url
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
handle: facebook
name: Facebook
sortOrder: 1
