field: 683b3f73-dc62-455c-9512-3ac50366b927 # Service Times
fieldLayouts:
  7d658987-ecb1-4f31-8df6-3d437f701a8f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 35c38b06-ce69-43d7-a836-76e6bf949e88 # Time
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6409e209-454a-43e9-8b5b-7307d9fa825c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 439f7a58-bc21-4e2a-bc90-871dbaf20470
        userCondition: null
fields:
  35c38b06-ce69-43d7-a836-76e6bf949e88: # Time
    columnSuffix: sbsuzvhr
    contentColumnType: text
    fieldGroup: null
    handle: time
    instructions: null
    name: Time
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: true
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: time
name: Time
sortOrder: 2
