columnSuffix: null
contentColumnType: string
fieldGroup: 776ccb4a-3f14-4b2c-be86-82f7a20d4e77 # Promo
handle: backgroundImage
instructions: ''
name: 'Background Image'
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds: null
  defaultUploadLocationSource: 'volume:a9bfaa8c-e93f-4a15-b2c5-f6f2caf578a8' # Background Image
  defaultUploadLocationSubpath: ''
  limit: ''
  localizeRelations: false
  previewMode: full
  restrictFiles: ''
  selectionLabel: ''
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:a9bfaa8c-e93f-4a15-b2c5-f6f2caf578a8' # Background Image
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:a9bfaa8c-e93f-4a15-b2c5-f6f2caf578a8' # Background Image
  targetSiteId: null
  useSingleFolder: true
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
