columnSuffix: rnugrayz
contentColumnType: integer(10)
fieldGroup: 65ee6975-465c-4135-a6e5-a45ce81a6535 # Promo
handle: intro_video_id
instructions: null
name: 'Intro Video ID'
searchable: false
settings:
  decimals: 0
  defaultValue: null
  max: null
  min: 0
  prefix: null
  previewCurrency: null
  previewFormat: none
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
