columnSuffix: null
contentColumnType: string
fieldGroup: cf39e5f6-a8bf-46aa-9b42-5f9bdc9efd43 # Pages
handle: relatedPages
instructions: ''
name: 'Related Pages'
searchable: false
settings:
  allowSelfRelations: false
  limit: ''
  localizeRelations: false
  selectionLabel: 'Select Pages to add to left menu'
  showSiteMenu: true
  source: null
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
