columnSuffix: zprnkwxc
contentColumnType: text
fieldGroup: 0759b0d2-7a69-4b31-9864-246df819554b # Series
handle: seriesSummary
instructions: null
name: 'Series Summary'
searchable: false
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  columnType: text
  defaultTransform: null
  initJs: null
  purifierConfig: null
  purifyHtml: true
  removeEmptyTags: false
  removeInlineStyles: false
  removeNbsp: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
