columnSuffix: null
contentColumnType: string
fieldGroup: 08256173-ec40-44f7-9b32-51e2d7eca2ed # Locations
handle: serviceTimes
instructions: null
name: 'Service Times'
searchable: false
settings:
  contentTable: '{{%matrixcontent_servicetimes}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
