columnSuffix: null
contentColumnType: string
fieldGroup: 28b7a08a-92c0-48ba-adec-f4b8fedd0a1d # Staff
handle: socialMedia
instructions: ''
name: 'Social Media'
searchable: false
settings:
  contentTable: '{{%matrixcontent_socialmedia}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
