columnSuffix: gmkznmew
contentColumnType: string(255)
fieldGroup: cabf5db1-8ddc-4576-b387-39d4366462cd # Message
handle: videoLink
instructions: null
name: 'Video Link'
searchable: false
settings:
  maxLength: 255
  types:
    - url
translationKeyFormat: null
translationMethod: none
type: craft\fields\Url
