fieldLayouts:
  ac11944e-c39e-4259-a2d2-856c043a1bbf:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 78106212-4541-48ce-9ff4-921c9077a54d # Social Media
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0d51ed9f-b32b-4b67-b791-83324cae89d0
            userCondition: null
            warning: null
            width: 100
        name: 'Sociale Handles'
        uid: c8edca6b-c464-4f6c-ae86-3b192f0ad944
        userCondition: null
handle: socialHandles
name: 'Social Handles'
sortOrder: 1
