defaultPlacement: end
enableVersioning: true
handle: forms
name: Forms
propagationMethod: all
siteSettings:
  9a595275-36b0-484a-b00f-9b3b8a2c12e8: # Generic Church
    enabledByDefault: true
    hasUrls: true
    template: forms/_entry
    uriFormat: '{slug}'
type: channel
