defaultPlacement: end
enableVersioning: true
handle: homeCards
name: 'Home Cards'
propagationMethod: all
siteSettings:
  9a595275-36b0-484a-b00f-9b3b8a2c12e8: # Generic Church
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
