defaultPlacement: end
enableVersioning: true
handle: staff
name: Staff
propagationMethod: all
siteSettings:
  9a595275-36b0-484a-b00f-9b3b8a2c12e8: # Generic Church
    enabledByDefault: true
    hasUrls: true
    template: staff/_entry
    uriFormat: 'staff/{slug}'
type: channel
